# script: run general pipeline script
# description: sources the general pipeline scripts, ensures project
# dependencies are installed and loaded, then builds configuration and creates
# required directories.

#' @title source general scripts
#' @description validates a character vector of script names, resolves each
#' script path from `r/0-general_pipeline`, validates file existence, sources
#' each script, and returns sourced paths invisibly.
#' @param script_names character vector with one or more script filenames,
#' validated with `checkmate::assert_character(any.missing = false, min.len = 1)`.
#' @return invisible character vector of sourced script paths.
#' @importFrom checkmate assert_character assert_file_exists
#' @importFrom purrr map_chr walk
#' @importFrom here here
#' @importFrom base source
#' @examples
#' source_general_scripts(c("00-dependencies.R", "01-setup.R"))
source_general_scripts <- function(script_names) {
  checkmate::assert_character(script_names, any.missing = FALSE, min.len = 1)

  script_paths <- script_names |>
    purrr::map_chr(function(script_name) {
      here::here("R", "0-general_pipeline", script_name)
    })

  script_paths |>
    purrr::walk(function(script_path) {
      checkmate::assert_file_exists(script_path)
      source(script_path, echo = FALSE)
    })

  invisible(script_paths)
}

#' @title run general pipeline
#' @description executes the general pipeline bootstrap by sourcing helper
#' scripts, installing missing dependencies, loading dependencies, creating the
#' configuration object, and creating required directories.
#' @return named list pipeline configuration generated by
#' `load_pipeline_config()`.
#' @examples
#' config <- run_general_pipeline()
#' names(config)
run_general_pipeline <- function() {
  general_scripts <- c(
    "00-dependencies.R",
    "01-setup.R",
    "02-helpers.R"
  )

  source_general_scripts(general_scripts)

  progress_bar <- create_progress_bar(total = 4, color = "green")

  check_dependencies(required_packages)
  progress_bar$tick(tokens = list(step = "check_dependencies"))

  load_dependencies(required_packages)
  progress_bar$tick(tokens = list(step = "load_dependencies"))

  config <- load_pipeline_config()
  progress_bar$tick(tokens = list(step = "load_pipeline_config"))

  create_required_directories(config$paths)
  progress_bar$tick(tokens = list(step = "create_required_directories"))

  config
}

config <- run_general_pipeline()
