# script: run general pipeline script
# description: sources the general pipeline scripts, ensures project
# dependencies are installed and loaded, then builds configuration and creates
# required directories.

if (!exists("get_pipeline_constants", mode = "function", inherits = TRUE)) {
  source(here::here("scripts", "0-general_pipeline", "01-setup.R"), echo = FALSE)
}


#' @title source general scripts
#' @description validates a character vector of script names, resolves each
#' script path from `scripts/0-general_pipeline`, validates file existence, sources
#' each script, and returns sourced paths invisibly.
#' @param script_names character vector with one or more script filenames,
#' validated with `checkmate::assert_character(any.missing = false, min.len = 1)`.
#' @return invisible character vector of sourced script paths.
#' @importFrom checkmate assert_character assert_file_exists
#' @importFrom purrr map_chr walk
#' @importFrom here here
#' @importFrom base source
#' @examples
#' source_general_scripts(c("00-dependencies.R", "01-setup.R"))
source_general_scripts <- function(script_names) {
  checkmate::assert_character(script_names, any.missing = FALSE, min.len = 1)

  script_paths <- script_names |>
    purrr::map_chr(function(script_name) {
      here::here("scripts", "0-general_pipeline", script_name)
    })

  script_paths |>
    purrr::walk(function(script_path) {
      checkmate::assert_file_exists(script_path)
      source(script_path, echo = FALSE)
    })

  return(invisible(script_paths))
}

#' @title run general pipeline
#' @description executes the general pipeline bootstrap by sourcing helper
#' scripts, installing missing dependencies, loading dependencies, creating the
#' configuration object, and creating required directories.
#' @param dataset_name character scalar dataset identifier forwarded to
#' `load_pipeline_config()` to build dataset-specific audit paths.
#' @return named list pipeline configuration generated by
#' `load_pipeline_config()`.
#' @importFrom progressr handlers handler_txtprogressbar with_progress progressor
#' @importFrom checkmate assert_string
#' @examples
#' config <- run_general_pipeline("fao_data_raw")
#' names(config)
run_general_pipeline <- function(dataset_name = get_pipeline_constants()$dataset_default_name) {
  checkmate::assert_string(dataset_name, min.chars = 1)
  pipeline_constants <- get_pipeline_constants()
  general_scripts <- pipeline_constants$script_names$general

  total_steps <- 5

  progressr::handlers(progressr::handler_txtprogressbar(
    width = 40,
    clear = FALSE
  ))

  config <- progressr::with_progress({
    progress <- progressr::progressor(along = seq_len(total_steps))

    source_general_scripts(general_scripts)
    progress("general pipeline: sourcing general scripts")

    check_dependencies(required_packages)
    progress("general pipeline: checking dependencies")

    load_dependencies(required_packages)
    progress("general pipeline: loading dependencies")

    config <- load_pipeline_config(dataset_name = dataset_name)
    progress("general pipeline: loading pipeline configuration")

    create_required_directories(config$paths)
    progress("general pipeline: creating required directories")

    config
  })

  return(config)
}

pipeline_constants <- get_pipeline_constants()

if (isTRUE(getOption(pipeline_constants$auto_run_options$general, TRUE))) {
  config <- run_general_pipeline()
}
